// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO347XK5YhbIXS1EIF7iO_T87EHP5KgcI',
    appId: '1:843128922357:android:0808edbf60f569b2bb65bc',
    messagingSenderId: '843128922357',
    projectId: 'carelink-1a1ee',
    storageBucket: 'carelink-1a1ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj2ngeJgwcme1j71LJxiLczkB4fk34b5A',
    appId: '1:843128922357:ios:d4cce113c279ad3fbb65bc',
    messagingSenderId: '843128922357',
    projectId: 'carelink-1a1ee',
    storageBucket: 'carelink-1a1ee.firebasestorage.app',
    iosBundleId: 'com.example.carelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADt27S2BwrZ_qkpVDCJS0s_QHMw6OeXcs',
    appId: '1:843128922357:web:8003b24886719e7bbb65bc',
    messagingSenderId: '843128922357',
    projectId: 'carelink-1a1ee',
    authDomain: 'carelink-1a1ee.firebaseapp.com',
    storageBucket: 'carelink-1a1ee.firebasestorage.app',
  );

}